### PR TITLE
2940: Replace office icon

### LINKED ISSUE #2940: Old icon for Behörde/Amt still shown on map
### Describe the Bug

The old icon for Behörde/Amt is still shown on the map. 

### Steps to Reproduce

1. Go to https://integreat.app/augsburg/de/locations?category=1
2. Zoom in
3. See that the icon on the map is still the hammer

### Expected Behavior

Icon shown on the map should be the building

### Actual Behavior

Icon shown on the map is still the hammer

### Additional Information

Old issue: https://github.com/digitalfabrik/integreat-app/issues/2657
Design: https://www.figma.com/design/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?node-id=1136-3404&node-type=frame&t=OfgTae7shTAdSJdk-0
CMS issue: https://github.com/digitalfabrik/integreat-cms/issues/2800

Icon should be what's seen in the top left, but is what's actually on the map.

image

### PR DESCRIPTION
**Pull request by steffenkleinle**
Replace office icon and update iconset.json.
Move multipoi icon to the right group.
Fixes https://github.com/digitalfabrik/integreat-app/issues/2940

### CODE REVIEW

**Review by ztefanie — APPROVED** [review]
Looks good. How can this be tested?

**Comment by steffenkleinle** [comment]
> Looks good. How can this be tested?

According to @f1sh1918 only by merging and deploying to production I think :/

**Review by LeandraH — APPROVED** [review]
Nothing quite like testing in production :D

**Review by f1sh1918 — APPROVED** [review]
looks good to me.
We don't have a testing environment so far
I guess one way could be to use this repo as a submodule as we do it in entitlementcard

**Pull request merged**
